import Section from "../components/Layout/Section";
import TermsSection from "../components/TermsSection";
import * as CONSTANTS from "../constants";

import classes from "./Terms.module.css";

const Terms = () => {
  const terms = [
    {
      title: "Terms & Conditions",
      writeups: [
        "Last Updated : January 18, 2022",
        `This website is operated by ${CONSTANTS.NAME}. Throughout the site, the term "${CONSTANTS.NAME_SHORT}", 
            "we", "us" or "our" as the context may require, refer to ${CONSTANTS.NAME}. By visiting our site and/or 
            purchasing something from us, you engage in our Service and agree to be bound by the following terms and conditions.`,
        `We reserve the right to update, change or replace any part of these Terms of services without prior written notice at 
            any time, and it is your responsibility to periodically review these Terms of Uses to stay informed of updates. 
            Any changes to the Terms will be in effect as of the last updated date referenced on the site.`,
        `Your continued use of this site after the last updated dates will constitute your acceptance of agreement.`,
        `By visiting the website of our products merchants, in particular www.opensea.io, you also engage and agree 
            to be bound by their terms and conditions.`,
        `This website is for informational purposes and serves as a binding contract for purchasers of ${CONSTANTS.NAME_SHORT} NFTs.`,
        `${CONSTANTS.NAME} sells pieces of a collection of digital artwork (NFTs) housed and run on the Polygon Network. 
            Users and Collector of these NFTs are solely responsible for the safety and the management of their own private assets, 
            which include but are not limited to Polygon Wallets, validating all transactions and contracts generated by this 
            website prior to and after purchases.`,
        `Users certify through purchase that they understand that, as the ${CONSTANTS.NAME_SHORT} smart contracts run on the 
            Polygon network and are bound by their system and terms, there is no ability to undo, reverse, or restore any transactions.`,
        `Any connected services included this website are provided “as is” and “as available” without any warranty of any kind. 
            Use of this website constitutes your agreement that you are accepting sole responsibility for any and all transactions 
            involving ${CONSTANTS.NAME} digital collectibles.`,
        `By agreeing to these Terms of Service, you represent that you are at least the age of majority in your state or province 
            of residence.`,
        `You may not use our products and/or services for any illegal or unauthorized purpose nor may you, in the use of the 
            Service, violate any laws in your jurisdiction (including but not limited to copyright laws).`,
      ],
    },
    {
      title: "Ownership",
      writeups: [
        `When you purchase your ${CONSTANTS.NAME} NFT, you own the NFT: the ownership is transferred to you on the Polygon 
        blockchain for that individual piece of Art, combination of traits and number. Ownership of the NFT is ruled by the smart 
        contract and the Ethereum Network terms.`,
      ],
    },
    {
      title: "Personal Usage",
      writeups: [
        `Subject to your continued acceptance with these terms, ${CONSTANTS.NAME_SHORT} allows you a worldwide, royalty-free 
    licence to use, copy and display the purchased Art, along with any derivative artwork or extensions that you could create or use, 
    limited by the following purposes : (i) for your own personal, non commercial use; (ii) as part of a marketplace that allows the 
    purchase and sales of your ${CONSTANTS.NAME} NFT, as long as the marketplace cryptographically verifies that you are the owner, 
    to ensure that only the actual owner have the right to display the Art; or (iii) as part of a third party website or application 
    that permits the inclusion, involvement or participation of your ${CONSTANTS.NAME_SHORT} NFT, provided that the website or the 
    application cryptographically verifies each ${CONSTANTS.NAME_SHORT} NFT owner’s right to display the Art for their NFT,
     to ensure that only the actual owner can display the Art, and provided that the Art is no longer visible once the actual owner 
     of the ${CONSTANTS.NAME} leave the website or application.`,
      ],
    },
    {
      title: "Commercial Usage",
      writeups: [
        `Subject to the actual owner of ${CONSTANTS.NAME} NFTs continued compliance with these Terms, ${CONSTANTS.NAME} grant you 
    an unlimited, worldwide licence to use, copy and display the purchased Art for the purpose of creating derivative works based upon 
    the Art. Examples of specified Commercial Use would be the use of the Art to produce and sell physical merchandise products 
    (T-Shirt, Posters, etc.) displaying copies of the purchased Art. Please be aware that nothing in this section will be deemed to 
    restrict you from (i) owning or operating a marketplace that permits the use and sale of ${CONSTANTS.NAME} generally, provided 
    that the marketplace cryptographically verifies each ${CONSTANTS.NAME_SHORT} NFT owner’s right to display the Art of their ${CONSTANTS.NAME_SHORT} NFT 
    to ensure that only the actual owner can display the Art; (ii) owning or operating a third party website or application that permits 
    the inclusion, involvement, or participation of ${CONSTANTS.NAME} generally, provided that the third party website or application 
    cryptographically verifies each ${CONSTANTS.NAME_SHORT} NFT owner’s rights to display the Art for their ${CONSTANTS.NAME} to ensure that 
    only the actual owner can display the Art, and provided that the Art is no longer visible once the owner of the purchased 
    ${CONSTANTS.NAME_SHORT} NFT leaves the website/application; or (iii) earning revenue from any of the foregoing.`,
        `However, you cannot use the artwork in connection with images of hatred, violence or any other inappropriate behavior. The License 
    granted in above only applies to the extent that you continue to own the relevant NFT. If at any time you trade, donate, giveaway, 
    transfer or otherwise dispose of your NFT for any reason, the license granted above will immediately expire, without notice, and you 
    will have no further right in or to the artwork of this NFT.`,
      ],
    },
    {
      title: `${CONSTANTS.NAME} IP`,
      writeups: [
        `Other than the rights to the Art, nothing gives you any rights to any other trademarks or other intellectual property rights 
belonging to ${CONSTANTS.NAME} including, without limitation ${CONSTANTS.NAME_SHORT} and the associated logos. All of these rights are 
expressly reserved in the name of ${CONSTANTS.NAME}.`,
      ],
    },
    {
      title: "Feedback",
      writeups: [
        `You can submit comments, bug reports, ideas about the site or the project. By submitting any feedback, you agree that we 
are free to use them in any way we choose without additional compensation to you and you hereby grant us a perpetual, irrevocable, 
nonexclusive worldwide licence to incorporate and use the feedback for any purpose.`,
      ],
    },
  ];

  return (
    <div className={classes.terms}>
      <Section>
        {terms.map((term) => (
          <TermsSection title={term.title} writeups={term.writeups} />
        ))}
      </Section>
    </div>
  );
};

export default Terms;
